# Generated by Django 5.0.3 on 2026-05-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyers",
            fields=[
                ("buyers_id", models.AutoField(primary_key=True, serialize=False)),
                ("buyer_name", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name": "Buyer",
                "verbose_name_plural": "Buyers",
                "db_table": "buyers",
            },
        ),
        migrations.CreateModel(
            name="Crops",
            fields=[
                ("crops_id", models.AutoField(primary_key=True, serialize=False)),
                ("crop_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WET", "Wet Season"),
                            ("DRY", "Dry Season"),
                            ("PERENNIAL", "Perennial"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("avg_yield_ton_ha", models.FloatField(blank=True, null=True)),
                (
                    "seed_cost_ngn_per_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop",
                "verbose_name_plural": "Crops",
                "db_table": "crops",
            },
        ),
        migrations.CreateModel(
            name="FarmBlocks",
            fields=[
                ("farm_blocks_id", models.AutoField(primary_key=True, serialize=False)),
                ("block_name", models.CharField(blank=True, max_length=100, null=True)),
                ("area_hectares", models.FloatField(blank=True, null=True)),
                ("geom_wkt", models.TextField(blank=True, null=True)),
                (
                    "soil_preparation_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Block",
                "verbose_name_plural": "Farm Blocks",
                "db_table": "farm_blocks",
            },
        ),
        migrations.CreateModel(
            name="Markets",
            fields=[
                ("markets_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "market_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Market",
                "verbose_name_plural": "Markets",
                "db_table": "markets",
            },
        ),
        migrations.CreateModel(
            name="Warehouses",
            fields=[
                ("warehouses_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("capacity_tons", models.FloatField(blank=True, null=True)),
                (
                    "storage_cost_per_ton_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "db_table": "warehouses",
            },
        ),
        migrations.CreateModel(
            name="WeatherStations",
            fields=[
                (
                    "weather_stations_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "station_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Weather Station",
                "verbose_name_plural": "Weather Stations",
                "db_table": "weather_stations",
            },
        ),
        migrations.CreateModel(
            name="CropDiseases",
            fields=[
                (
                    "crop_diseases_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "disease_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                (
                    "crops_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diseases",
                        to="core.crops",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Disease",
                "verbose_name_plural": "Crop Diseases",
                "db_table": "crop_diseases",
            },
        ),
        migrations.CreateModel(
            name="DiseaseReports",
            fields=[
                ("reports_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("report_date", models.DateField(blank=True, null=True)),
                (
                    "treatment_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("affected_area_hectares", models.FloatField(blank=True, null=True)),
                (
                    "crop_diseases_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.cropdiseases",
                    ),
                ),
                (
                    "farm_blocks_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_reports",
                        to="core.farmblocks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Report",
                "verbose_name_plural": "Disease Reports",
                "db_table": "disease_reports",
            },
        ),
        migrations.AddField(
            model_name="crops",
            name="farm_blocks_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crops",
                to="core.farmblocks",
            ),
        ),
        migrations.CreateModel(
            name="Farmers",
            fields=[
                ("farmers_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("lga", models.CharField(blank=True, max_length=100, null=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                (
                    "farm_blocks_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.farmblocks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farmer",
                "verbose_name_plural": "Farmers",
                "db_table": "farmers",
            },
        ),
        migrations.CreateModel(
            name="Farms",
            fields=[
                ("farms_id", models.AutoField(primary_key=True, serialize=False)),
                ("farm_name", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("lga", models.CharField(blank=True, max_length=100, null=True)),
                ("area_hectares", models.FloatField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("geom_wkt", models.TextField(blank=True, null=True)),
                (
                    "land_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateField(blank=True, null=True)),
                (
                    "farmers_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farms",
                        to="core.farmers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
                "db_table": "farms",
            },
        ),
        migrations.AddField(
            model_name="farmers",
            name="farms_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farmers",
                to="core.farms",
            ),
        ),
        migrations.CreateModel(
            name="FarmEquipment",
            fields=[
                (
                    "farm_equipment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "equipment_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("BROKEN", "Broken"),
                            ("RETIRED", "Retired"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Equipment",
                "verbose_name_plural": "Farm Equipment",
                "db_table": "farm_equipment",
            },
        ),
        migrations.AddField(
            model_name="farmblocks",
            name="farms_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="core.farms",
            ),
        ),
        migrations.CreateModel(
            name="ExportShipments",
            fields=[
                (
                    "export_shipments_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantity_tons", models.FloatField(blank=True, null=True)),
                ("export_date", models.DateField(blank=True, null=True)),
                (
                    "freight_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "insurance_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "customs_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "buyers_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="core.buyers",
                    ),
                ),
                (
                    "crops_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.crops",
                    ),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Shipment",
                "verbose_name_plural": "Export Shipments",
                "db_table": "export_shipments",
            },
        ),
        migrations.CreateModel(
            name="DroneFlights",
            fields=[
                (
                    "drone_flights_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "drone_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DJI_MAVIC", "DJI Mavic"),
                            ("DJI_PHANTOM", "DJI Phantom"),
                            ("DJI_INSPIRE", "DJI Inspire"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("pilot", models.CharField(blank=True, max_length=100, null=True)),
                ("flight_date", models.DateField(blank=True, null=True)),
                (
                    "flight_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drone_flights",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drone Flight",
                "verbose_name_plural": "Drone Flights",
                "db_table": "drone_flights",
            },
        ),
        migrations.AddField(
            model_name="crops",
            name="farms_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crops",
                to="core.farms",
            ),
        ),
        migrations.CreateModel(
            name="ClimateEvents",
            fields=[
                (
                    "climate_events_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLOOD", "Flood"),
                            ("DROUGHT", "Drought"),
                            ("HEAVY_RAIN", "Heavy Rain"),
                            ("WINDSTORM", "Windstorm"),
                            ("EXTREME_HEAT", "Extreme Heat"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("impact", models.TextField(blank=True, null=True)),
                (
                    "damage_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climate_events",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Climate Event",
                "verbose_name_plural": "Climate Events",
                "db_table": "climate_events",
            },
        ),
        migrations.CreateModel(
            name="FarmWorkers",
            fields=[
                (
                    "farm_workers_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIELD_WORKER", "Field Worker"),
                            ("SUPERVISOR", "Supervisor"),
                            ("FARM_MANAGER", "Farm Manager"),
                            ("HARVESTER", "Harvester"),
                            ("EQUIPMENT_OPERATOR", "Equipment Operator"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "daily_rate_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "farm_blocks_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.farmblocks",
                    ),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Worker",
                "verbose_name_plural": "Farm Workers",
                "db_table": "farm_workers",
            },
        ),
        migrations.CreateModel(
            name="FertilizerApplications",
            fields=[
                (
                    "fertilizer_applications_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fertilizer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NPK", "NPK"),
                            ("UREA", "Urea"),
                            ("DAP", "DAP"),
                            ("POTASH", "Potash"),
                            ("COMPOST", "Compost"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("amount_kg", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "application_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "farm_blocks_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fertilizer_apps",
                        to="core.farmblocks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fertilizer Application",
                "verbose_name_plural": "Fertilizer Applications",
                "db_table": "fertilizer_applications",
            },
        ),
        migrations.CreateModel(
            name="FinancialSummary",
            fields=[
                (
                    "financial_summary_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("total_yield_tons", models.FloatField(blank=True, null=True)),
                (
                    "avg_selling_price_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_revenue_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_costs_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "net_profit_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("roi_percentage", models.FloatField(blank=True, null=True)),
                ("calculation_date", models.DateField(blank=True, null=True)),
                (
                    "crops_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.crops",
                    ),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_summaries",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Summary",
                "verbose_name_plural": "Financial Summaries",
                "db_table": "financial_summary",
            },
        ),
        migrations.CreateModel(
            name="IrrigationSystems",
            fields=[
                (
                    "irrigation_systems_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "system_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRIP", "Drip Irrigation"),
                            ("SPRINKLER", "Sprinkler System"),
                            ("SURFACE", "Surface Irrigation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "water_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOREHOLE", "Borehole"),
                            ("WELL", "Well"),
                            ("RIVER", "River"),
                            ("RESERVOIR", "Reservoir"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("coverage_hectares", models.FloatField(blank=True, null=True)),
                (
                    "installation_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_systems",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Irrigation System",
                "verbose_name_plural": "Irrigation Systems",
                "db_table": "irrigation_systems",
            },
        ),
        migrations.CreateModel(
            name="Loans",
            fields=[
                ("loans_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("interest_rate", models.FloatField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAID", "Paid"),
                            ("DEFAULTED", "Defaulted"),
                            ("PENDING", "Pending"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "farmers_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="core.farmers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "db_table": "loans",
            },
        ),
        migrations.CreateModel(
            name="MarketPrices",
            fields=[
                (
                    "market_prices_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "price_per_ton_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "crops_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="core.crops",
                    ),
                ),
                (
                    "markets_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="core.markets",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Price",
                "verbose_name_plural": "Market Prices",
                "db_table": "market_prices",
            },
        ),
        migrations.CreateModel(
            name="NdviRecords",
            fields=[
                (
                    "ndvi_records_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("capture_date", models.DateField(blank=True, null=True)),
                ("mean_ndvi", models.FloatField(blank=True, null=True)),
                ("min_ndvi", models.FloatField(blank=True, null=True)),
                ("max_ndvi", models.FloatField(blank=True, null=True)),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ndvi_records",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "NDVI Record",
                "verbose_name_plural": "NDVI Records",
                "db_table": "ndvi_records",
            },
        ),
        migrations.CreateModel(
            name="PesticideApplications",
            fields=[
                (
                    "pesticide_applications_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("chemical", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pesticide_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HERBICIDE", "Herbicide"),
                            ("INSECTICIDE", "Insecticide"),
                            ("FUNGICIDE", "Fungicide"),
                            ("RODENTICIDE", "Rodenticide"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("amount_liters", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "farm_blocks_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesticide_apps",
                        to="core.farmblocks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesticide Application",
                "verbose_name_plural": "Pesticide Applications",
                "db_table": "pesticide_applications",
            },
        ),
        migrations.CreateModel(
            name="Plantings",
            fields=[
                ("plantings_id", models.AutoField(primary_key=True, serialize=False)),
                ("planting_date", models.DateField(blank=True, null=True)),
                ("expected_harvest", models.DateField(blank=True, null=True)),
                ("seed_quantity_kg", models.FloatField(blank=True, null=True)),
                (
                    "planting_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("plant_spacing_cm", models.IntegerField(blank=True, null=True)),
                ("row_spacing_cm", models.IntegerField(blank=True, null=True)),
                (
                    "crops_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantings",
                        to="core.crops",
                    ),
                ),
                (
                    "farm_blocks_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantings",
                        to="core.farmblocks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planting",
                "verbose_name_plural": "Plantings",
                "db_table": "plantings",
            },
        ),
        migrations.CreateModel(
            name="SatelliteImages",
            fields=[
                (
                    "satellite_images_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "satellite_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SENTINEL-2", "Sentinel-2"),
                            ("LANDSAT-8", "Landsat-8"),
                            ("LANDSAT-9", "Landsat-9"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("capture_date", models.DateField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "image_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satellite_images",
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satellite Image",
                "verbose_name_plural": "Satellite Images",
                "db_table": "satellite_images",
            },
        ),
        migrations.CreateModel(
            name="SoilZones",
            fields=[
                ("soil_zones_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "soil_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOAMY", "Loamy"),
                            ("CLAY", "Clay"),
                            ("SANDY", "Sandy"),
                            ("SILTY", "Silty"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("ph", models.FloatField(blank=True, null=True)),
                ("organic_matter", models.FloatField(blank=True, null=True)),
                (
                    "farm_blocks_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.farmblocks",
                    ),
                ),
                (
                    "farms_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.farms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Zone",
                "verbose_name_plural": "Soil Zones",
                "db_table": "soil_zones",
            },
        ),
        migrations.CreateModel(
            name="SoilTests",
            fields=[
                ("tests_id", models.AutoField(primary_key=True, serialize=False)),
                ("nitrogen_ppm", models.FloatField(blank=True, null=True)),
                ("phosphorus_ppm", models.FloatField(blank=True, null=True)),
                ("potassium_ppm", models.FloatField(blank=True, null=True)),
                ("test_date", models.DateField(blank=True, null=True)),
                (
                    "test_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("lab_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "soil_zones_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="core.soilzones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Test",
                "verbose_name_plural": "Soil Tests",
                "db_table": "soil_tests",
            },
        ),
        migrations.CreateModel(
            name="WeatherRecords",
            fields=[
                (
                    "weather_records_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("rainfall_mm", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                (
                    "weather_stations_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="core.weatherstations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Record",
                "verbose_name_plural": "Weather Records",
                "db_table": "weather_records",
            },
        ),
        migrations.CreateModel(
            name="WorkerPayments",
            fields=[
                (
                    "worker_payments_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("payment_period_start", models.DateField(blank=True, null=True)),
                ("payment_period_end", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("MOBILE_MONEY", "Mobile Money"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "farm_workers_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.farmworkers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Payment",
                "verbose_name_plural": "Worker Payments",
                "db_table": "worker_payments",
            },
        ),
        migrations.CreateModel(
            name="WorkerTasks",
            fields=[
                (
                    "worker_tasks_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("task_description", models.TextField(blank=True, null=True)),
                ("date_assigned", models.DateField(blank=True, null=True)),
                ("hours_worked", models.FloatField(blank=True, null=True)),
                (
                    "task_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "farm_workers_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.farmworkers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Task",
                "verbose_name_plural": "Worker Tasks",
                "db_table": "worker_tasks",
            },
        ),
        migrations.CreateModel(
            name="Yields",
            fields=[
                ("yields_id", models.AutoField(primary_key=True, serialize=False)),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("yield_tons", models.FloatField(blank=True, null=True)),
                (
                    "harvest_cost_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PREMIUM", "Premium"),
                            ("STANDARD", "Standard"),
                            ("BASIC", "Basic"),
                            ("REJECT", "Rejected"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "plantings_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yields",
                        to="core.plantings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yield",
                "verbose_name_plural": "Yields",
                "db_table": "yields",
            },
        ),
    ]
